pipeline {
  agent any

  environment {
    IMAGE_NAME = "charafedd20/backend-app"
  }

  stages {
    stage('Clone repository') {
      steps {
        git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/m-elhamlaoui/development-platform-jihane.git'
      }
    }

    stage('Build Backend') {
      steps {
        dir('backend') {
          sh './mvnw clean package -DskipTests'
        }
      }
    }

    stage('Build Docker image') {
      steps {
        dir('backend') {
          sh 'export PATH=$PATH:/usr/local/bin && docker build -t $IMAGE_NAME .'
        }
      }
    }

    stage('Push Docker image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
           sh 'export PATH=$PATH:/usr/local/bin && echo $PASSWORD | docker login -u $USERNAME --password-stdin'
           sh 'export PATH=$PATH:/usr/local/bin && docker push $IMAGE_NAME'

        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        script {
          docker.image('bitnami/kubectl:latest').inside(
            "--user=0:0 " +
            "-v /root/.kube:/root/.kube:ro " +
            "-v /root/.minikube:/root/.minikube:ro"
          ) {
            sh 'kubectl get nodes --kubeconfig=/root/.kube/config'
            sh 'kubectl apply -f k8s/backend-deployment.yaml --kubeconfig=/root/.kube/config'
            sh 'kubectl apply -f k8s/backend-service.yaml --kubeconfig=/root/.kube/config'
          }
        }
      }
    }
  }
}
