apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ismaimadani/beyondearth-backend:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/development_platform"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dev_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dev_password"
