apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  jwt-secret: bExQcmFSOXFxWlNqM0IwTktEbnYyUkIwa1ZnNnZsMFhsTFByYVI5cXFaU2ozQjBBS0RudjJSQjBrVmc2dmwwWA==
---
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
type: Opaque
data:
  username: YWRtaW4=
  password: UGFzc3dvcmQyMDIwKys=
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
type: Opaque
data:
  cloud-name: ZGdyeWMybWdx
  api-key: NjczOTI1MzUxNjMyMzc3
  api-secret: dS0tRTh1U1FsdWk1cG5kLUNROEI0ZV9DN1BV
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  admin-password: YWRtaW4=