services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: development-platform-jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_config:/var/jenkins_config
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network
    restart: unless-stopped

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: development-platform-jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${JENKINS_AGENT_SECRET}
      - JENKINS_AGENT_NAME=docker-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    depends_on:
      - jenkins
    restart: unless-stopped

  # SonarQube for code quality
  sonarqube:
    image: sonarqube:community
    container_name: development-platform-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - jenkins-network
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:13
    container_name: development-platform-sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - jenkins-network

  # Nexus Repository for artifacts
  nexus:
    image: sonatype/nexus3:latest
    container_name: development-platform-nexus
    ports:
      - "8082:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonar_db_data:
  nexus_data:

networks:
  jenkins-network:
    driver: bridge 